package org.hyperion.hype;

public enum TokenType {
  // Single-character tokens.
  LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
  LEFT_BRACKET, RIGHT_BRACKET, COMMA, DOT, MINUS,
  PLUS, SEMICOLON, COLON, SLASH, STAR, MODULO,

  // One or two character tokens.
  BANG, BANG_EQUAL,
  EQUAL, EQUAL_EQUAL,
  GREATER, GREATER_EQUAL,
  LESS, LESS_EQUAL,
  PLUS_PLUS, MINUS_MINUS,

  // Literals.
  IDENTIFIER, STRING, NUMBER,

  // Keywords.
  AND, CLASS, ELSE, FALSE, FN, FOR, IF, NIL, OR,
  RETURN, SUPER, THIS, TRUE, VAR, WHILE,

  EOF
}
